[
    {
        "_id": "5f0c940a5efd5b42c47ea10f",
        "venueName": "Kieler Schloss",
        "venueStreet": "Wall",
        "venuePostal": "24143",
        "venueCity": "Kiel2323",
        "contactPerson": "Vorname Nachname",
        "contactPhone": "4567890",
        "contactMobile": "6666666",
        "contactMail": "mail@provider.com",
        "loadingPath": "lange 50m",
        "storage": "Hinterbühne",
        "parking": "LKW-Parkplatz neben Ladetor",
        "osm": "Hier kommt Karte irgendwann",
        "stageWidth": "8",
        "stageDepth": "18",
        "stageHeight": "27",
        "stageLevel": "5",
        "availableTech": "vorhandene Technik Kieler Schloss",
        "stageLeft": "Strom Buehnelinks Hinterbühne",
        "StageRight": "Strom BuehneRechts Hinterbühne",
        "createdAt": "2020-07-13T17:04:10.625Z",
        "updatedAt": "2020-07-14T11:44:19.520Z",
        "__v": 0
    },
    {
        "_id": "5f0c9a865efd5b42c47ea110",
        "venueName": "Kieler Schloss",
        "venueStreet": "Wall",
        "venuePostal": "24143",
        "venueCity": "Kiel",
        "contactPerson": "Vorname Nachname",
        "contactPhone": "4567890",
        "contactMobile": "6666666",
        "contactMail": "mail@provider.com",
        "loadingPath": "lange 50m",
        "storage": "Hinterbühne",
        "parking": "LKW-Parkplatz neben Ladetor",
        "osm": "Hier kommt Karte irgendwann",
        "stageWidth": "8",
        "stageDepth": "18",
        "stageHeight": "27",
        "stageLevel": "5",
        "availableTech": "vorhandene Technik Kieler Schloss",
        "stageLeft": "Strom Buehnelinks Hinterbühne",
        "StageRight": "Strom BuehneRechts Hinterbühne",
        "createdAt": "2020-07-13T17:31:50.924Z",
        "updatedAt": "2020-07-13T17:31:50.924Z",
        "__v": 0
    },